#:schema https://raw.githubusercontent.com/yunanwg/brilliant-CV/main/metadata.toml.schema.json

#import "@preview/fontawesome:0.6.0"
# Set the output language
# INFO: value must matches folder suffix; i.e "zh" -> "./modules_zh"
language = "fr"

[layout]
    # Optional values: skyblue, red, nephritis, concrete, darknight
    # You can also use a custom color by hex code i.e. "#1E90FF"
    awesome_color = "darknight"

    # Skips are for controlling the spacing between sections and entries
    before_section_skip = "1pt"
    before_entry_skip = "1pt"
    before_entry_description_skip = "1pt"

    # Optional: sets paper size and margins. Possible values: a4 (default), us-letter
    paper_size = "a4"

    # Optional: sets the width of the right column of a cvEntry. If not set, values known to work well are used
    #date_width = "3.6cm"

    [layout.fonts]
        regular_fonts = ["Source sans 3"]
        header_font = "Roboto"

    [layout.header]
        # Optional values: left, center, right
        header_align = "left"

        # Decide if you want to display profile photo or not
        display_profile_photo = true
        # Radius in % to clip profile photo at
        profile_photo_radius = "50%"
        info_font_size = "11pt"

    [layout.entry]
        # Decide if you want to put your company in bold or your position in bold
        display_entry_society_first = true

        # Decide if you want to display organisation logo or not
        display_logo = true

    [layout.footer]
        # Decide if you want to display page counter or not
        display_page_counter = false

        # Decide if you want to display the footer or not
        display_footer = true


[inject]
    # Decide if you want to inject AI prompt or not
    inject_ai_prompt = false

    # Decide if you want to inject keywords or not
    inject_keywords = true
    injected_keywords_list = ["Data Analyst", "Data Scientist", "Data Engineer", "R", "Python", "SQL", "VBA/Excel", "Power BI", "Data Science", "Modélisation", "Estimation", "Communication", "Synthèse", "modélisation", "churn rate", "analysis", "communication", "valorisation des données", "Extraction", "Nettoyage", "Visualisation et Analyse de données", "Big Data", "Modélisation", "Machine learning/ IA", "Segmentation", "Churn", "Scrum Master", "DevOps", "Optimisation", "requêtes SQL", "tableau de bord", "Aisance orale", "Autonomie", "Adaptabilité", "Esprit d'analyse", "Esprit de synthèse", "Orientation résultat", "Persévérance", "Extraction", "Negociation", "Vente", "Visualisation et Analyse de données", "Big Data", "Segmentation", "Typologie", "Taux de Churn", "HEC", "Polytechnique", "ENSAI", "Ecole National de la Statistique et de l'Analyse Economique","ENS", "École d'ingénieur", "Marketing", "Management", "Business"]

[personal]
    first_name = "Rilwanou"
    last_name = "MAHAMAN"


      [personal.info]
        location = "France"
        email = "rilwanouan5@gmail.com"
        phone = "+33 6 15 44 21 78"
        linkedin = "ril-eng"
        gitlab = "ril-lab"
        github = "ril-hub46"
        
        #homepage = "johndoe.dev"
        #orcid = "0000-0000-0000-0000"
        # researchgate = "John-Doe"
        
        # extraInfo = "Available for remote work"
        
        # Custom info with awesome icon
        #[personal.info.custom-1]
            # image = "" # Example: image("./path/to/image.png")
            #awesomeIcon = "graduation-cap" # Example: "graduation-cap" see https://typst.app/universe/package/fontawesome/
            #text = "PhD in Data Science"
            #link = "https://www.example.com"
            
        # Custom info with image icon
        #[personal.info.custom-2]
            # image = image("./path/to/custom-icon.png") # Custom image icon
            #awesomeIcon = "certificate"
            #text = "AWS Certified"
            #link = "https://aws.amazon.com/certification/"
            
        # Linebreak example - adds a line break in header info
        # linebreak = ""

# add a new section if you want to include the language of your choice
# i.e. [[lang.ru]]
# each section must contains the following fields

[lang.de]
    header_quote = "Erfahrener Datenanalyst sucht ab sofort eine Vollzeitstelle"
    cv_footer = "Lebenslauf"
    letter_footer = "Anschreiben"

[lang.en]
    header_quote = "Experienced Data Analyst looking for a full time job starting from now"
    cv_footer = "Curriculum vitae"
    letter_footer = "Cover letter"

[lang.fr]
    header_quote = "Ingénieur Data à la recherche d’un stage de fin d’étude de 6 mois à partir de mars 2026."
    cv_footer = "Résumé"
    letter_footer = "Lettre de motivation"

[lang.zh]
    header_quote = "具有丰富经验的数据分析师，随时可入职"
    cv_footer = "简历"
    letter_footer = "申请信"

[lang.it]
    header_quote = "Senior data analyst attualmente disponibile per una posizione di lavoro full-time"
    cv_footer = "Curriculum vitae"
    letter_footer = "Lettera di presentazione"

 # For languages that are not written in Latin script
 # Currently supported non-latin language codes: ("zh", "ja", "ko", "ru")
[lang.non_latin]
    name = "王道尔"
    font = "Heiti SC"
